version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  commit-message:
    prefix: "poetry"
    prefix-development: "poetry dev"
    include: "scope"
